### ISSUE TITLE
Add support for binary format

### ISSUE THREAD

**Issue by DradeAW** [esedaghatnejad/psort#4]
Hi,

I want to give Psort a try, but all of my data are in binary format (`.bin` or `.dat`).

Is it possible to add support for binary format?
All you would need is a pop-up to ask for the type, the factor to µV, and the sampling rate.

Thanks,
Aurélien

**Comment by esedaghatnejad** [comment]
If you have the libraries to load your data in Python, it should be easy to add it to Psort.
The process of loading starts in
psort/gui/signals.py/onToolbar_load_ButtonClick, line 630
but the actual implementation is in
/psort/utils/lib.py/LoadData, line 230

you can take a look at 
/psort/utils/lib.py/load_file_matlab, line 111
for a similar example to your case.

**Comment by esedaghatnejad** [comment]
In the
psort/gui/signals.py/load_process_finished_complement, line 1433
I have some examples on how to present a pop-up window, ask for an input, and then change the database based on the values provided by the user. In my case, I ask for a scale factor and then scale the ch_data to put it in 100-10,000 range.

**Comment by DradeAW** [comment]
> If you have the libraries to load your data in Python, it should be easy to add it to Psort.

What libraries are you talking about?
I just load my data using `data = np.fromfile("filename", dtype=np.int16).reshape(...)` (in my case I have multiple channels).

I'll take a look and try to code something, thanks!

**Comment by esedaghatnejad** [comment]
You do not necessary need to provide specific libraries for interacting with your files. I was just talking about a general case.

Psort interacts with .smr files. Those files also contain multiple channels and a pop-up window asks for the channel of interest.
Please take a look and let me know should you need more help.
