### ISSUE TITLE
Several broken bits of code

### ISSUE THREAD

**Issue by m-beau** [esedaghatnejad/psort#5]
Hi,

I managed to start the gui only after editing the code because of broken imports:
- numpy 1.20.3 exclusively is required: (the line np.array(['min'], dtype=np.unicode) in /utils/dictionnaries.py breaks with earlier versions, and numba breaks with versions>=1.21) - it should be hard-coded the requirements.txt
- every QtGui.QFrame needs to be replaced by QtWidgets.QFrame
- every QtGui.QSizePolicy by QtWidgets.QSizePolicy
- numba doesn't compile at /psort/dependencies/umap_package/layouts.py:29 for some reason, so I had to switch from hard no-python mode (@njit) to a soft compiler (@jit)

Cheers!

**Comment by GulatiLab** [comment]
Thanks for this. We were having a really hard time getting this to work but once we make those changes it ran. However it would fail to load data until we also made one addition correction:

- every QtGui.QMessageBox needs to be replaced by QtWidgets.QMessageBox

**Comment by esedaghatnejad** [comment]
@GulatiLab @m-beau 
Thank you for your interest in using P-sort. Very sorry for the inconveniences.
I have addressed these issues in my local code but did not get time to polish it and push it to GitHub. Soon, I will update the README and repo accordingly to avoid further confusions. Thanks. --Ehsan

**Comment by esedaghatnejad** [comment]
In the meantime, please download the updated code using this DropBox link:
https://www.dropbox.com/s/erg097778d863dz/psort-master.zip?dl=0

Then please follow the following instructions to work with the software.
##########################################
Download the zip file and unzip it.
Download the most recent version of the Anaconda from https://www.anaconda.com
Open the Anaconda Prompt (Windows) or Terminal (Mac and Linux)

Navigate to the psort-master folder where setup.py is located.
In my Mac system I did
`cd ~/Downloads/psort-master`

Activate the base environment. Usually the Anaconda opens in base env by default and you do not need to do this.
`conda activate base`

Remove the psort env if you already have created one. If this is your first time, skip this step.
`conda env remove -n psort`

Make a new environment called psort and install python 3.7 inside of it.
`conda create -n psort python=3.7`

Activate the psort env.
`conda activate psort`

Install the following packages:
`conda install pyqtgraph`
`conda install -c conda-forge umap-learn`
`conda install pytables`
`conda install decorator`
`conda install matplotlib`

If you want to change the source code, then run the psort from the source code:
`python -m psort`

If you do not want to change the source code, install the psort program:
`python setup.py install`

By typing psort, you can run the program.
`psort`

In the future, if you already have install the psort, first uninstall the old version and then install the new version.
`pip uninstall psort`

The next time that you open the Anaconda Prompt, it is usually in the base env. You need to activate the psort env, first.
`conda activate psort`

Run the psort either by
`python -m psort`
or if you installed it, then by
`psort`

**Comment by esedaghatnejad** [comment]
@GulatiLab  @m-beau 
The problems are two folds. The recent version of Numba is incompatible with Numpy and also the embedded version of umap-learn. To solve the issue, we install umap-learn package directly and it will install a compatible Numba and Numpy with itself.
The pip version of the PyQt is different than the Conda version. If you pip install PyQt you will face some difficulties.
In the new code, we will install psort in an isolated env to avoid all those conflicts and incompatibilities.
Please let me know if this solves the problems.

**Comment by esedaghatnejad** [comment]
I should also mention that after sorting a channel, you will save a `.psort` file to disk. You can read those `.psort` files in Matlab using the codes provided in the `matlab_codes` folder.
Specifically, read through `Psort_plot_cellSummary.m` to get an understanding of how to work with the `.psort` file.

**Comment by esedaghatnejad** [comment]
@GulatiLab @m-beau
Please clone P-sort v1.0.8. Thanks.
